# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b21bd93049f920073f08f5d4a2addde7d52a4d4506ba25b4fbf38ce5ef7ffbe03bce649c34db1e62a22f821dab9614121c3b394003870a16bed9b99073d06cfd

test:
  secret_key_base: c00435e9c638fcc5b6cfe910a48f064365fe26592f832349d7550944a0dd0cecc2a20e7ba1293467715b51f33111aa76324e769ddeae1f899c761137b729ad3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
